import { StyleSheet } from 'react-native';

export const financeStyles = StyleSheet.create({
  // FinanceHeader
  headerContainer: {
    padding: 24,
    paddingTop: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#121212',
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: -1,
    color: 'white',
  },
  closeButton: {
    padding: 8,
    backgroundColor: '#202020',
    borderRadius: 12,
  },
  closeButtonText: { color: '#888', fontWeight: 'bold' },

  // ValueInput
  valueContainer: {
    alignItems: 'center',
    marginBottom: 32,
    width: '100%',
  },
  valueTitle: {
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: '900',
    color: '#888',
    letterSpacing: 2,
    marginBottom: 8,
  },
  valueTouchable: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  currencySymbol: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#666',
    marginRight: 4,
  },
  valueText: {
    fontSize: 60,
    fontWeight: '900',
    letterSpacing: -2,
  },
  hiddenInput: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0,
    color: 'transparent',
  },

  // CategoryGrid
  gridContainer: { width: '100%', gap: 12 },
  gridTitle: {
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: '900',
    color: '#888',
    letterSpacing: 2,
    textAlign: 'center',
  },
  gridInner: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  categoryButton: {
    width: '30%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
  },
  categoryText: {
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: 8,
    letterSpacing: -0.5,
  },

  // SuccessOverlay
  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(18, 18, 18, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  successIconBg: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    elevation: 10,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: -0.5,
    color: 'white',
  },
  successSubtitle: { color: '#9CA3AF', marginTop: 8 },

  // Finance Screen (AddTransaction)
  financeTypeRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  financeTypeBtn: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 16,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  financeTypeBtnText: { fontWeight: 'bold' },
  vehicleSection: { marginBottom: 32, width: '100%' },
  vehicleTitle: {
    color: '#888',
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: '900',
    letterSpacing: 2,
    marginBottom: 12,
    textAlign: 'center',
  },
  vehicleScrollView: {
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  vehicleBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    marginRight: 10,
  },
  vehicleBtnText: { fontWeight: 'bold', fontSize: 12 },
  addCategoryBtn: { marginTop: 24, alignItems: 'center' },
  addCategoryBtnText: { fontWeight: 'bold', fontSize: 12 },

  // AdicionarCategoria Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    width: '100%',
    backgroundColor: '#161616',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#333',
  },
  modalTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalLabel: {
    color: '#888',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  modalInput: {
    backgroundColor: '#0A0A0A',
    borderWidth: 1,
    borderRadius: 12,
    color: '#FFF',
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
  },
  modalButtonsRow: { flexDirection: 'row', gap: 12 },
  modalBtnCancel: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#222',
    alignItems: 'center',
  },
  modalBtnCancelText: { color: '#FFF', fontWeight: 'bold' },
  modalBtnSave: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalBtnSaveText: {
    color: '#0A0A0A',
    fontWeight: 'bold',
  },
  modalIconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
    justifyContent: 'center',
  },
  modalIconOption: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0A0A0A',
    borderWidth: 2,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
